# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIeMQ5Qntnql4G_Tp0u0pBZ9sX9pRjRf
"""

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

print("1D Array:", arr1)
print("Dimensions:", arr1.ndim)
print("Data Type:", arr1.dtype)

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("2D Array:")
print(arr2)
print("Dimensions:", arr2.ndim)
print("Shape:", arr2.shape)
print("Data Type:", arr2.dtype)

arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("3D Array:")
print(arr3)
print("Dimensions:", arr3.ndim)
print("Shape:", arr3.shape)
print("Data Type:", arr3.dtype)

print("First element:", arr1[0])
print("Third element:", arr1[2])

print("2D array element:", arr2[1, 2])

print("First three elements:", arr1[:3])
print("Last two elements:", arr1[-2:])

print("First two rows:")
print(arr2[:2])

print("First two columns:")
print(arr2[:, :2])

arr = np.arange(1, 13)

print("Original Array:")
print(arr)

reshaped = arr.reshape(3, 4)

print("Reshaped Array:")
print(reshaped)

zeros_array = np.zeros((3, 3))

print(zeros_array)

ones_array = np.ones((2, 4))

print(ones_array)

numbers = np.arange(1, 11, 2)

print(numbers)

numbers = np.linspace(0, 10, 5)

print(numbers)

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

numbers = np.array([1, 2, 3, 4, 5])

print("Original:", numbers)
print("Square:", numbers ** 2)
print("Multiply by 10:", numbers * 10)
print("Add 5:", numbers + 5)

numbers = np.array([10, 15, 20, 25, 30, 35])

mask = numbers > 20

print("Mask:", mask)
print("Numbers greater than 20:", numbers[mask])

numbers = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

result = numbers + 10

print("Original Array:")
print(numbers)

print("After Broadcasting:")
print(result)

numbers = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Minimum:", np.min(numbers))
print("Maximum:", np.max(numbers))
print("Median:", np.median(numbers))

data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Median:", np.median(data))

marks = np.array([78, 85, 92, 67, 88, 76, 95, 81])

print("Marks:", marks)
print("Average Marks:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))
print("Median Marks:", np.median(marks))

print("Students scoring above 80:")
print(marks[marks > 80])

print("NumPy practice completed successfully!")